name: sme_fin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  dotted_border: ^3.1.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Navigation
  go_router: ^17.0.1

  # Network
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  connectivity_plus: ^7.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Dependency Injection
  get_it: ^9.2.0

  # Functional Programming
  dartz: ^0.10.1

  # Image Handling
  extended_image: ^10.0.1
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0

  # File Handling
  file_picker: ^10.3.8

  # Utils
  intl: ^0.20.2

  # Debugging
  logger: ^2.6.1

# Flutter Splash Screen Setup
#
# This configuration helps you create a splash screen for your Flutter project.
#
# Instructions:
# 1. Add the following configuration to your pubspec.yaml file.
# 2. Run the command: fvm dart run flutter_native_splash:create
# 3. If you make any changes to the splash screen configuration, re-run the command.
#
# Current-Configuration:
flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
